### ISSUE TITLE
Can start sdl_server, but page does not display

### ISSUE THREAD

**Issue by jackwilliambell** [smartdevicelink/sdl_server#16]
I've managed to get sdl_server running on both an Ubuntu machine and an OSX machine. In both cases, when I navigate to http://localhost/3000 I get an empty page. Doing a view source shows it has loaded a page with a long list of javascript dependencies, but nothing that will display. I get the same results with multiple browsers, including several different versions of Firefox, the latest Chrome and the latest Safari.

In Firefox, if I bring up the developer console, it shows the following error:

`Error: [$injector:modulerr] http://errors.angularjs.org/1.2.16/$injector/modulerr?p0=SDL&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.16%2F%24injector%2Fmodulerr%3Fp0%3Dui.router%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.2.16%252F%2524injector%252Fnomod%253Fp0%253Dui.router%250At%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A6%253A450%250AYc%252Fb.module%253C%252F%253C%252Fb%255Be%255D%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A20%253A260%250AYc%252Fb.module%253C%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A20%253A1%250Ae%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A33%253A1%250Aq%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A7%253A278%250Ae%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A32%253A445%250Ae%252F%253C%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A33%253A18%250Aq%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A7%253A278%250Ae%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A32%253A445%250Aac%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A36%253A34%250A%2524b%252Fc%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A17%253A431%250A%2524b%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A18%253A140%250AWc%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A17%253A215%250A%2540http%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.16%252Fangular.min.js%253A209%253A360%250An.Callbacks%252Fj%2540http%253A%252F%252Fcode.jquery.com%252Fjquery-1.11.0.min.js%253A2%253A27131%250An.Callbacks%252Fk.fireWith%2540http%253A%252F%252Fcode.jquery.com%252Fjquery-1.11.0.min.js%253A2%253A27949%250A.ready%2540http%253A%252F`

**Comment by jackwilliambell** [comment]
More detail -- Error output from sdl_server includes the following:

```
Warning:  You requested a route '/libs/angular-toggle-switch/angular-toggle-switch.min.js' that does not exist or was not handled.  Ensure at least one route calls 'sender.setResponse(data, req, res, next);'
[ 404 ] Method or Request not found.
[ 500 ] Error: Method or Request not found.
    at createAndSendError (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/foxjs/libs/Server/send.js:128:13)
    at handle404 (/Users/jbell/Documents/Code/sdl/sdl_server/server/app/error/error_controller.js:71:14)
    at callbacks (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:167:11)
    at callbacks (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:165:11)
    at param (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:167:11)
    at sendResponse (/Users/jbell/Documents/Code/sdl/sdl_server/server/app/response/response_controller.js:20:7)
    at callbacks (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/jbell/Documents/Code/sdl/sdl_server/server/node_modules/express/lib/router/index.js:145:5)

```

**Comment by jackwilliambell** [comment]
More information -- Looking over the error output from sdl_server it is clear there are a lot of things missing from the libs directory beyond the angular library. When I look at the libs directory in the server created by fox I only see one item: error/index.js.

This is also true in the downloaded clone of sdl_server I started from and on the Github repo. So either there are a lot of missing libraries or a significant number of undocumented dependencies we are supposed to install and properly set up.

**Comment by jackwilliambell** [comment]
Update -- I've been trying all kinds of things. I was able to install all the missing components via Bower, but the 'fox new' command didn't pick them up. I finally resolved it properly by doing a fresh 'fox new' and then copying the missing components by hand into the libs/ directory of the new server instance *BEFORE* I did the first page load to localhost:3000.

However, even with all the dependencies loading into the browser I am still getting a blank page. 

Question: Has anyone been able to get this working using the code in this repo and the startup instructions? I'm far from a node expert, so that might be part of my problem, but it looks to me like there are a lot of undocumented dependencies and steps here that might be specific to one developer's machine.

Missing libs I hand-installed:

- angular-file-upload

- angular-toggle-switch

- angular-ui-router

- bootstrap

- ng-table

**Comment by CMaylone** [comment]
@ssmereka went through and refactored the code the code this week and most of those dependencies are not required anymore. Make sure you are using the latest code by running the following from your `sdl_server` directory

```bash
git pull
git checkout master
npm install
npm start
```

**Comment by jackwilliambell** [comment]
Thanks @CMaylone. Those steps got it working, at least to the extent I am seeing a home screen with a button marked 'Perform Request' that makes an example policy request. I also see that the readme has been updated to match, which is good. Thank you

Of course, now that I have it running I have more questions:

1. The previous version looked like it had user pages to maintain the policy data. But this version definitely doesn't; is that intentional? Will they be added back in or is the server intended primarily to support development of sdl_core?

2. I am able to run the server without Mongo DB, does that mean it is no longer required?

3. Related to previous two questions: it looks like the policy data is contained in a JSON file, are we supposed to update that file to add applications and such to the policy data? File is located at /data/policies/default.json

4. I don't think I understand HMI Levels. I thought I did, but they way they are used surprises me, so can you update the wiki page for HMI Levels? (Existing Policies documentation in the wiki links to a page for HMI Levels, but the link goes to an empty page.)

Thanks again for your quick response.

**Comment by ssmereka** [comment]
The SDL Server is not, and was never, meant to be a production server.  It is instead to serve as a reference to how SDL core requests policy table updates from an SDL server.  It is up to each adopter of SDL to create their own implementation of SDL server to fit their organizations needs.  Why?  Well, among many reasons, the largest is we cannot create a single server that will meet all adopter's SDL and IT needs.

> Note:  We are waiting for a bug fix in either core and/or the mobile libraries to get the SDL server rewrite up and running.

1.  We have intentionally simplified the server.  The [Previous Version](https://github.com/smartdevicelink/sdl_server/tree/old) is no longer maintained.
2.  A database is no longer required.
3. Instead of dynamically building the policy JSON file, we are serving static ones.  This is to greatly simplify the server making it easier to show how a policy update request works.  You can of course change the policy file or create new ones.
4. I added a page for [HMI levels](https://github.com/smartdevicelink/sdl_server/wiki/HMI-Levels).  The [SDL Core Integration Guidelines](https://app.box.com/s/ohcgjv61cykgkuhycglju6cc4efr0ym3) can also give you a better idea of how HMI levels work.

@stefanek22 maybe you can offer a better description of HMI levels.

**Comment by ssmereka** [comment]
Closing this question, we can always reopen if you have further questions or discussion.
