### ISSUE TITLE
Synchronize Application Categories lookup table from SHAID

### ISSUE THREAD

**Issue by russjohnson09** [smartdevicelink/sdl_server#164]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
The App Category Lookup table is currently hard-coded and not kept in sync using the respective SHAID API endpoint. Recommend updating the table to add the `name` column (to align with SHAID's structure) and add logic to periodically pull and upsert category data from SHAID.

##### Reproduction Steps
1.  Add a new category to SHAID.
2. The sdl server will not update on startup.

##### Expected Behavior
Whenever the shaid server is updated, the sdl server should be checking against it on startup or daily through cron jobs.

##### Observed Behavior
The categories are not updated.

##### OS, Browser & Version Information
NA

##### Test Case, Sample Code, and / or Example App
NA

**Comment by theresalech** [comment]
Closed via #165
