### ISSUE TITLE
[SDL 0240] WebEngine support for SDL JavaScript

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_server#178]
Proposal: [WebEngine support for SDL JavaScript](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0240-sdl-js-pwa.md)

> This proposal is adding a new transport to the SDL JavaScript library to support (progressive) web apps to run on a WebEngine or a browser.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/767

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- When formatting `locales` in the `manifest.json` file, use standard [(RFC 5646)](https://tools.ietf.org/html/rfc5646), and convert locale strings when necessary.
- Do not specify the location of the manifest's <script> tag placement within the proposal.
- All revisions included in this PR: https://github.com/smartdevicelink/sdl_evolution/pull/888/files
> The proposal .md file was updated to reflect these revisions on 12/19/19.

**Comment by LuxoftAKutsan** [comment]
@theresalech  I do not see any policy struct changes in https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0240-sdl-js-pwa.md. Looks like sdl_server cloud functionality is enough for WebEngine support. 
Should we close this task?

**Comment by theresalech** [comment]
@LuxoftAKutsan the Project Maintainer will handle any necessary changes to the sdl_server, as noted in the [SDL_Releases](https://github.com/smartdevicelink/sdl_evolution/blob/master/SDL_Releases.md) document. 
 Please leave this issue open.  Thanks!

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0240 Revisions - WebEngine support for SDL JavaScript](smartdevicelink/sdl_evolution#923). These revisions change the `appID` parameter within `GetAppProperties` to `policyAppID` and add a minlength of `1` to the param. Please see the proposal markdown file for more details.

**Comment by theresalech** [comment]
Closed via #184
