### ISSUE TITLE
Cannot GET /policy

### ISSUE THREAD

**Issue by lixiaozhang** [smartdevicelink/sdl_server#18]
I got a error that the browser has only displayed "Cannot GET /policy"  as address to "http://localhost:3000/policy" after finished the quick guide steps .
System environment : win7 x64

**Comment by ssmereka** [comment]
1. Please make sure you have the latest code. e.g. run a  ```git pull```
2. Can you provide the node console logs and the browser's console logs.

**Comment by lixiaozhang** [comment]
I have fixed it,i have copied all of the code of the files( './app/policy/policy_api.js'&'policy_client') into the file(./index.js) ,it have run; i think the router may be wrong,Thank you!
[index.txt](https://github.com/smartdevicelink/sdl_server/files/179448/index.txt)

**Comment by ssmereka** [comment]
Glad you were able to get it working.  Could you provide the error logs you were seeing so we can fix any issues that exist?

**Comment by lixiaozhang** [comment]
Sorry, No any log files or errors are reported, just a 'Cannot get /policy' message in browser, Could you check the code 
`crave.directory(path.resolve("./app"), [ "model", "api", "client" ], start, app, config, log);`（the end line of  file 'index.js'）, it may  be useless,Thank you!

**Comment by ssmereka** [comment]
The line is correct and works on Mac OSx and the Linux versions I have tested.  I'll see if someone can test the lastest code on Windows.  

The line basically scans the ```apps``` folder and loads all the files, in order, with the specified suffix (e.g. ```policy_model```).  Might be an issue on your machine or windows machines in general with file paths, permissions, or etc.

**Comment by ssmereka** [comment]
SDL server should now work properly on windows.  

I had to update the submodule [crave](https://github.com/ssmereka/crave) to work with windows directory structure.

Reference Commit:  2bb582c7bd2a3e6745aded7cdc3cf58c60c35c2d
