### ISSUE TITLE
Outdated SDL Server set-up documentatio

### ISSUE THREAD

**Issue by sztankatt** [smartdevicelink/sdl_server#20]
Hi!

I am followig the guide here https://github.com/smartdevicelink/sdl_core/tree/develop, and it seems that the guide is a bit outdated for the sdl_server.

After starting up the server I get 404 erros for http://localhost:3000/cars, http://localhost:3000/modules.json,  http://localhost:3000/apps. Also the link https://github.com/smartdevicelink/sdl_server/blob/master/docs/application_launching_v1.0.md dos not exist.

Best,
Tamas

**Comment by ssmereka** [comment]
We already talked in the SDL slack, but I'll put my response here for everyone to see.

"Currently the example SDL server does not have application launching built into it.  The example SDL server was stripped down to a bare bones server to provide a better example of how SDL policies work"

@JackLivio or @justinjdickow can you please make sure the SDL core docs are updated.

**Comment by nickschwab** [comment]
Closing this issue, as it references a very old version of the Policy Server. The latest Policy Server release contains support for approving and denying applications.

**Comment by justinjdickow** [comment]
@ssmereka No
