### ISSUE TITLE
[SDL 0293] Enable OEM exclusive apps support

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_server#225]
**Proposal:** [Enable OEM exclusive apps support](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0293-vehicle-type-filter.md)

> This feature will enable SDL adopters to provide exclusive apps to their users depending on vehicle type. The proposal describes a way to share vehicle type information before sending the Register App Interface request.

**Review:** https://github.com/smartdevicelink/sdl_evolution/issues/971

**Steering Committee Decision:** 
The Steering Committee voted to accept this proposal with the following revisions:

The author is to update the proposal to include the requested requirement for the Java Suite Library to have two pull requests submitted for this feature. The reasoning as to why is documented in [this comment ](https://github.com/smartdevicelink/sdl_evolution/issues/971#issuecomment-730557977)and should be included in the proposal.

The proposal .md file was updated to reflect these revisions on 12/14/2020.

**Comment by KhrystynaDubovyk** [comment]
@jordynmackool, @crokita could you please specify what changes are expected for sdl_server within this proposal?
I can see the revision https://github.com/smartdevicelink/sdl_evolution/pull/1105 was merged, but still, sdl_server is not mentioned in `Impacted Platforms` and nothing mentioned about the server changes throughout the proposal.
many thanks in advance.

**Comment by jordynmackool** [comment]
@KhrystynaDubovyk there are no changes for SHAID or the Server as the proposal stands. 

[Revisions](https://github.com/smartdevicelink/sdl_evolution/pull/1106) to this proposal have been submitted for Steering Committee review, if accepted by the Steering Committee changes may be needed then.

**Comment by jordynmackool** [comment]
Closing as there were no changes needed for the Server for this feature.
