### ISSUE TITLE
JSON examples are invalid.

### ISSUE THREAD

**Issue by ChernyshovYuriy** [smartdevicelink/sdl_server#3]
JSON examples that are located at:
https://github.com/smartdevicelink/sdl_server/blob/master/docs/application_launching_v1.0.md
and which are used in the responses are invalid formatted.

For example, these JSON's are invalid:
- The successful response will contain a JSON object
- Example Android response

To validate JSON please use http://json.parser.online.fr/

**Comment by ssmereka** [comment]
Thank you for submitting an issue.  They are actually valid, the parser just doesn't like that the property values are not encapsulated in quotes.  So for example:  ```{ status: "OK" }```  and ```{ "status": "OK" }``` are both valid JSON, however the parser you use does not accept the first example.  Only invalid property names such as ```"foo bar"``` and ```"foo-bar"``` must be encapsulated in quotes.

But I can add the quotes if it helps.

**Comment by ChernyshovYuriy** [comment]
Hi.
Yes, I knew that.
Just according to JSON documentation (http://www.json.org/) the Key in Object must be String.
Thank's for fixing it :-)
