### ISSUE TITLE
App usage data collection & reporting

### ISSUE THREAD

**Issue by nickschwab** [smartdevicelink/sdl_server#98]
Core has references to the ability to send aggregated app usage data to a Policy Server during Policy Table update requests. If this data is available in a Policy Table update, the Policy Server should record the information and present it in a meaningful way to OEMs.

Storing this data will likely create a large amount of additional database I/O activity which may or may not be suitable to all OEM partners, so data collection and reporting should be optional.

**Comment by theresalech** [comment]
Issue created for implementation of related evolution proposal: https://github.com/smartdevicelink/sdl_server/issues/132.  Closing this issue as a duplicate.
